### ISSUE TITLE
Sample app doesn't creating database and/or related tables if then don't exist

### ISSUE THREAD

**Issue by iSatishYadav** [adamosoftware/Postulate.Mvc#2]
Either add a feature to create required databases or specify scripts for creating them in documentation.

**Comment by adamosoftware** [comment]
hmmm I didn't expect anyone to care! Let me think about that

**Comment by adamosoftware** [comment]
I know it's been a while, but the [Startup,Configuration](https://github.com/adamosoftware/Postulate.Mvc/blob/master/SampleWebApp/Startup.cs#L24) method now creates the database and seed data. More documentation in the readme to follow soon
